import MainLayout from "@/components/MainLayout";
import { UploadVideo } from "@/modules/UploadVideo";
import Head from "next/head";
import React from "react";

const Upload = () => {
  return (
    <>
      <Head>
        <title>tik tik</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <MainLayout>
          <UploadVideo />
        </MainLayout>
      </main>
    </>
  );
};

export default Upload;
