import MainLayout from "@/components/MainLayout";
import { Profile } from "@/modules/Profile";
import { IParams, IUser, IVideo } from "@/utils/types";
import axios from "axios";
import Head from "next/head";
import { FC } from "react";

interface UserProps {
  user: IUser;
  userVideos: IVideo[];
  userLikedVideos: IVideo[];
}

const User: FC<UserProps> = ({ user, userVideos, userLikedVideos }) => {
  return (
    <>
      <Head>
        <title>tik tik</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <MainLayout>
          <Profile user={user} myVideos={userVideos} likedVideos={userLikedVideos} />
        </MainLayout>
      </main>
    </>
  );
};

export const getServerSideProps = async ({ params: { id } }: IParams) => {
  const { data } = await axios.get(`${process.env.NEXT_PUBLIC_CLIENT_URL}/api/user/${id}`);
  return {
    props: { ...data },
  };
};

export default User;
