import MainLayout from "@/components/MainLayout";
import { Videos } from "@/modules/Videos";
import useUserStore from "@/store/userStore";
import { IParams, IVideo, NextPageWithLayout } from "@/utils/types";
import axios from "axios";
import Head from "next/head";
import React, { ReactElement } from "react";

interface SearchProps {
  videos: IVideo[];
}

const Search: NextPageWithLayout<SearchProps> = ({ videos }) => {
  const {} = useUserStore();

  return (
    <>
      <Head>
        <title>tik tik</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Videos videos={videos} />
      </main>
    </>
  );
};

Search.getLayout = function (page: ReactElement) {
  return <MainLayout>{page}</MainLayout>;
};

export const getServerSideProps = async ({ params: { searchTerm } }: IParams) => {
  const { data } = await axios.get<IVideo[]>(
    `${process.env.NEXT_PUBLIC_CLIENT_URL}/api/search/${searchTerm}`
  );
  return {
    props: { videos: data },
  };
};

export default Search;
