import Head from "next/head";
import React from "react";

const Detail = () => {
  return (
    <>
      <Head>
        <title>tik tik</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        Detail
      </main>
    </>
  );
};

export default Detail;
