import MainLayout from "@/components/MainLayout";
import { VideoDetail } from "@/modules/VideoDetail";
import { IParams, IVideo, NextPageWithLayout } from "@/utils/types";
import axios from "axios";
import Head from "next/head";
import { ReactElement } from "react";

interface DetailProps {
  video: IVideo;
}

const Detail: NextPageWithLayout<DetailProps> = ({ video }) => {
  return (
    <>
      <Head>
        <title>tik tik</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <VideoDetail video={video} />
      </main>
    </>
  );
};

export const getServerSideProps = async ({ params: { id } }: IParams) => {
  const { data } = await axios.get<IVideo>(`${process.env.NEXT_PUBLIC_CLIENT_URL}/api/post/${id}`);
  return {
    props: { video: data },
  };
};

export default Detail;
